language: node_js
os:
  - windows
  - linux
  - osx
node_js:
  - "node"
  - 10
  - 8
  - 6
matrix:
## An ENOMEM error occurs with 11.6.0 under Travis-CI for Windows.
## Disable until we can determine the cause.
#  include:
#    - os: windows
#      node_js: "latest"
  exclude:
    - os: windows
      node_js: "node"
git:
  depth:
    1

after_script:
  - "cat ./coverage/lcov.info | ./node_modules/.bin/coveralls"
