environment:
  matrix:
    - nodejs_version: '6' # stable
    - nodejs_version: '4' # LTS
install:
  - ps: Install-Product node $env:nodejs_version
  - npm cache clear
  - npm i npm@5 -g
  - set PATH=%APPDATA%\npm;%PATH%
  - set CI=true
  - npm config set progress=false
  - set PATH=%APPDATA%\npm;%PATH%
  - npm install
matrix:
  fast_finish: true
build: off
version: '{build}'
shallow_clone: true
clone_depth: 1
test_script:
  - node --version
  - npm --version
  - npm test
